In [1]:
a1 = [1, 2, 3, 4, 5]
type(a1)

list

In [2]:
import numpy as np
a2 = np.array(a1)

In [3]:
a2

array([1, 2, 3, 4, 5])

In [4]:
type(a2)

numpy.ndarray

In [5]:
a2.ndim

1

In [6]:

a2.shape

(5,)

In [7]:
b1 = [[4, 5, 6, 7],
      [9, 10, 11, 12]]
type(b1)

list

In [8]:
b2 = np.array(b1)

In [9]:
b2

array([[ 4,  5,  6,  7],
       [ 9, 10, 11, 12]])

In [10]:
b2.ndim

2

In [11]:
b2.shape

(2, 4)

In [12]:
c1 = [[[1, 2, 3, 4],
       [4, 5, 6, 7],
       [9, 10, 11, 12]],
       
      [[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]]]
type(c1

_IncompleteInputError: incomplete input (3542075969.py, line 8)

In [13]:
c1 = [[[1, 2, 3, 4],
       [4, 5, 6, 7],
       [9, 10, 11, 12]],
       
      [[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]]]
type(c1)

list

In [14]:
c2 = np.array(c1)
c2

array([[[ 1,  2,  3,  4],
        [ 4,  5,  6,  7],
        [ 9, 10, 11, 12]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [15]:
type(c2)

numpy.ndarray

In [16]:
c2.ndim

3

In [17]:
c2.shape

(2, 3, 4)

In [18]:
d1 = [[2, 3, 4, 5],
      [6, 7, 8, 9],
      [10, 11, 12, 13]]
d2 = np.array(d1)

In [19]:
d2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [20]:
d2.shape

(3, 4)

In [21]:
3*4

12

In [22]:

d2.reshape(2, 6)

array([[ 2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13]])

In [23]:

d2.reshape(6, 2)

array([[ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13]])

In [24]:

d2.reshape(6, 2, 1)

array([[[ 2],
        [ 3]],

       [[ 4],
        [ 5]],

       [[ 6],
        [ 7]],

       [[ 8],
        [ 9]],

       [[10],
        [11]],

       [[12],
        [13]]])

In [25]:
a = [5, 6, 7, 8, 9, 10, 11]
type(a)

list

In [26]:
a*3

[5, 6, 7, 8, 9, 10, 11, 5, 6, 7, 8, 9, 10, 11, 5, 6, 7, 8, 9, 10, 11]

In [27]:
b = []
for i in a:
    b.append(i*3)

In [28]:
b

[15, 18, 21, 24, 27, 30, 33]

In [29]:
c = [i*3 for i in a]
c

[15, 18, 21, 24, 27, 30, 33]

In [30]:
a1 = np.array(a)
a1

array([ 5,  6,  7,  8,  9, 10, 11])

In [31]:
a1*3

array([15, 18, 21, 24, 27, 30, 33])

In [32]:

3*a1 + 5

array([20, 23, 26, 29, 32, 35, 38])

In [33]:
a1**2

array([ 25,  36,  49,  64,  81, 100, 121])

In [34]:
a1**(1/2)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479])

In [35]:
d = [12, 13, 11, 15, 14]
type(d)

list

In [36]:
# Initialize product by 1
p = 1

# Apply for loop
for i in d:
    p = p*i


In [37]:
p

360360

In [38]:
d

[12, 13, 11, 15, 14]

In [39]:

12*13*11*15*14

360360

In [40]:
np.prod(d)

np.int64(360360)

In [41]:
e1 = [[2, 3, 4, 5],
      [6, 7, 8, 9],
      [11, 13, 12, 22]]
e2 = np.array(e1)

In [42]:
e2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [11, 13, 12, 22]])

In [43]:
np.sum(e2)

np.int64(102)

In [44]:
e3 = np.sum(e2, axis=0)
e3

array([19, 23, 24, 36])

In [45]:

np.sum(e2, axis=1)

array([14, 30, 58])

In [46]:

np.mean(e2)

np.float64(8.5)

In [47]:

np.mean(e2, axis=0)

array([ 6.33333333,  7.66666667,  8.        , 12.        ])

In [48]:
np.mean(e2, axis=1)

array([ 3.5,  7.5, 14.5])

In [49]:
np.median(e2)

np.float64(7.5)

In [50]:

np.median(e2, axis=0)

array([6., 7., 8., 9.])

In [51]:

np.median(e2, axis=1)

array([ 3.5,  7.5, 12.5])

In [52]:

np.max(e2)

np.int64(22)

In [53]:

np.min(e2)

np.int64(2)

In [54]:

np.max(e2, axis=0)

array([11, 13, 12, 22])

In [55]:

np.max(e2, axis=1)

array([ 5,  9, 22])

In [56]:
np.std(e2)

np.float64(5.283622494715786)